Repository kanchoz/Konkuk_Hackathon, pull requests merged in 2023-08, with the labels that each got.

#5 [Fix] fix crash
  FrontEnd/PopUp/PopUp/HomeView/View/Main/Base.lproj/Main.storyboard
  FrontEnd/PopUp/PopUp/HomeView/View/Main/PieceCollectionViewCell.swift
  FrontEnd/PopUp/PopUp/HomeView/View/Main/PieceDetailTableViewCell.swift
  FrontEnd/PopUp/PopUp/HomeView/View/Main/PieceTableViewCell.swift
  FrontEnd/PopUp/PopUp/HomeView/View/Main/PieceViewController.storyboard
Labels: bug

#6 [Fix] bug
  FrontEnd/PopUp/PopUp.xcodeproj/project.pbxproj
  FrontEnd/PopUp/PopUp/Assets.xcassets/PieceTab.imageset/Contents.json
  FrontEnd/PopUp/PopUp/Assets.xcassets/PieceTab.imageset/PieceTab.png
  FrontEnd/PopUp/PopUp/Assets.xcassets/pieceBtnCollection.imageset/Contents.json
  FrontEnd/PopUp/PopUp/Assets.xcassets/pieceBtnCollection.imageset/PieceCollectionBtn.png
  FrontEnd/PopUp/PopUp/Assets.xcassets/pieceBtnTable.imageset/Contents.json
  FrontEnd/PopUp/PopUp/Assets.xcassets/pieceBtnTable.imageset/PieceTableBtn.png
  FrontEnd/PopUp/PopUp/Assets.xcassets/verticalDotsBtn.imageset/Contents.json
  FrontEnd/PopUp/PopUp/Assets.xcassets/verticalDotsBtn.imageset/verticalDotsBtn.png
  FrontEnd/PopUp/PopUp/HomeView/Controller/Piece/PieceDetailViewController.swift
  FrontEnd/PopUp/PopUp/HomeView/Controller/Piece/PieceNavigationController.swift
  FrontEnd/PopUp/PopUp/HomeView/Controller/Piece/PieceViewController.swift
  FrontEnd/PopUp/PopUp/HomeView/Controller/Piece/PieceViewController2.swift
  FrontEnd/PopUp/PopUp/HomeView/View/Main/Base.lproj/Main.storyboard
Labels: bug

#11 MainView 필터 구현 및 PieceView AutoLayout 수정
  FrontEnd/PopUp/PopUp.xcodeproj/project.pbxproj
  FrontEnd/PopUp/PopUp/Assets.xcassets/CancleBtn.imageset/CancleBtn.png
  FrontEnd/PopUp/PopUp/Assets.xcassets/CancleBtn.imageset/CancleBtn@2x.png
  FrontEnd/PopUp/PopUp/Assets.xcassets/CancleBtn.imageset/CancleBtn@3x.png
  FrontEnd/PopUp/PopUp/Assets.xcassets/CancleBtn.imageset/Contents.json
  FrontEnd/PopUp/PopUp/Assets.xcassets/filter.imageset/Contents.json
  FrontEnd/PopUp/PopUp/Assets.xcassets/filter.imageset/filter.png
  FrontEnd/PopUp/PopUp/Assets.xcassets/filter.imageset/filter@2x.png
  FrontEnd/PopUp/PopUp/Assets.xcassets/filter.imageset/filter@3x.png
  FrontEnd/PopUp/PopUp/HomeView/Controller/Main/PopupFilterViewController.swift
  FrontEnd/PopUp/PopUp/HomeView/Controller/Main/ViewController.swift
  FrontEnd/PopUp/PopUp/HomeView/Controller/ViewController.swift
  FrontEnd/PopUp/PopUp/HomeView/View/Main/Base.lproj/Main.storyboard
  FrontEnd/PopUp/PopUp/HomeView/View/Main/PieceViewController.storyboard
Labels: bug, enhancement

#15 Piece Detail Info, Review
  FrontEnd/PopUp/PopUp.xcodeproj/project.pbxproj
  FrontEnd/PopUp/PopUp/Assets.xcassets/Color/G2.colorset/Contents.json
  FrontEnd/PopUp/PopUp/Assets.xcassets/Color/G3.colorset/Contents.json
  FrontEnd/PopUp/PopUp/Assets.xcassets/FloatingBtn/backBtn.imageset/Contents.json
  FrontEnd/PopUp/PopUp/Assets.xcassets/FloatingBtn/backBtn.imageset/backBtn.png
  FrontEnd/PopUp/PopUp/Assets.xcassets/FloatingBtn/backBtn.imageset/backBtn@2x.png
  FrontEnd/PopUp/PopUp/Assets.xcassets/FloatingBtn/backBtn.imageset/backBtn@3x.png
  FrontEnd/PopUp/PopUp/Assets.xcassets/bookmark.imageset/Contents.json
  FrontEnd/PopUp/PopUp/Assets.xcassets/bookmark.imageset/bookmark.png
  FrontEnd/PopUp/PopUp/Assets.xcassets/bookmark.imageset/bookmark@2x.png
  FrontEnd/PopUp/PopUp/Assets.xcassets/bookmark.imageset/bookmark@3x.png
  FrontEnd/PopUp/PopUp/Assets.xcassets/newjeansPopupImage.imageset/Contents.json
  FrontEnd/PopUp/PopUp/Assets.xcassets/newjeansPopupImage.imageset/newjeansPopupImage.png
  FrontEnd/PopUp/PopUp/Assets.xcassets/newjeansPopupImage.imageset/newjeansPopupImage@2x.png
  FrontEnd/PopUp/PopUp/Assets.xcassets/newjeansPopupImage.imageset/newjeansPopupImage@3x.png
  FrontEnd/PopUp/PopUp/Assets.xcassets/reviewImage/Contents.json
  FrontEnd/PopUp/PopUp/Assets.xcassets/reviewImage/downArrow.imageset/Contents.json
  FrontEnd/PopUp/PopUp/Assets.xcassets/reviewImage/downArrow.imageset/downArrow.png
  FrontEnd/PopUp/PopUp/Assets.xcassets/reviewImage/downArrow.imageset/downArrow@2x.png
  FrontEnd/PopUp/PopUp/Assets.xcassets/reviewImage/downArrow.imageset/downArrow@3x.png
  FrontEnd/PopUp/PopUp/Assets.xcassets/reviewImage/events.imageset/Contents.json
  FrontEnd/PopUp/PopUp/Assets.xcassets/reviewImage/events.imageset/events.png
  FrontEnd/PopUp/PopUp/Assets.xcassets/reviewImage/events.imageset/events@2x.png
  FrontEnd/PopUp/PopUp/Assets.xcassets/reviewImage/events.imageset/events@3x.png
  FrontEnd/PopUp/PopUp/Assets.xcassets/reviewImage/eyes.imageset/Contents.json
  FrontEnd/PopUp/PopUp/Assets.xcassets/reviewImage/eyes.imageset/waiting 1.png
  FrontEnd/PopUp/PopUp/Assets.xcassets/reviewImage/eyes.imageset/waiting 2.png
  FrontEnd/PopUp/PopUp/Assets.xcassets/reviewImage/eyes.imageset/waiting.png
  FrontEnd/PopUp/PopUp/Assets.xcassets/reviewImage/thumb.imageset/Contents.json
  FrontEnd/PopUp/PopUp/Assets.xcassets/reviewImage/thumb.imageset/thumb.png
  FrontEnd/PopUp/PopUp/Assets.xcassets/reviewImage/thumb.imageset/thumb@2x.png
  FrontEnd/PopUp/PopUp/Assets.xcassets/reviewImage/thumb.imageset/thumb@3x.png
  FrontEnd/PopUp/PopUp/Assets.xcassets/reviewImage/upperArrow.imageset/Contents.json
  FrontEnd/PopUp/PopUp/Assets.xcassets/reviewImage/upperArrow.imageset/upperArrow.png
  FrontEnd/PopUp/PopUp/Assets.xcassets/reviewImage/upperArrow.imageset/upperArrow@2x.png
  FrontEnd/PopUp/PopUp/Assets.xcassets/reviewImage/upperArrow.imageset/upperArrow@3x.png
  FrontEnd/PopUp/PopUp/Assets.xcassets/reviewImage/waiting.imageset/Contents.json
  FrontEnd/PopUp/PopUp/Assets.xcassets/reviewImage/waiting.imageset/waiting.png
  FrontEnd/PopUp/PopUp/Assets.xcassets/reviewImage/waiting.imageset/waiting@2x.png
  FrontEnd/PopUp/PopUp/Assets.xcassets/reviewImage/waiting.imageset/waiting@3x.png
  FrontEnd/PopUp/PopUp/HomeView/Controller/Main/ViewController.swift
  FrontEnd/PopUp/PopUp/HomeView/Controller/PieceInfo/PieceInfoViewController.swift
  FrontEnd/PopUp/PopUp/HomeView/View/Main/Base.lproj/Main.storyboard
  FrontEnd/PopUp/PopUp/HomeView/View/Main/PieceCollectionViewCell.swift
  FrontEnd/PopUp/PopUp/HomeView/View/Main/PieceViewController.storyboard
  FrontEnd/PopUp/PopUp/HomeView/View/PieceInfo/PieceInfoCollectionViewCell.swift
  FrontEnd/PopUp/PopUp/HomeView/View/PieceInfo/PieceInfoTableViewCell.swift
  FrontEnd/PopUp/PopUp/HomeView/View/PieceInfo/PieceInfoViewController.storyboard
Labels: enhancement

#16 Feat/piece info view
  FrontEnd/PopUp/PopUp.xcodeproj/project.pbxproj
  FrontEnd/PopUp/PopUp.xcodeproj/project.xcworkspace/xcuserdata/idonghyeon.xcuserdatad/UserInterfaceState.xcuserstate
  FrontEnd/PopUp/PopUp/Assets.xcassets/리뷰 접기더보기/Contents.json
  FrontEnd/PopUp/PopUp/Assets.xcassets/리뷰 접기더보기/ReviewDown.imageset/Contents.json
  FrontEnd/PopUp/PopUp/Assets.xcassets/리뷰 접기더보기/ReviewDown.imageset/icon_NAV (31).png
  FrontEnd/PopUp/PopUp/Assets.xcassets/리뷰 접기더보기/ReviewDown.imageset/icon_NAV (32).png
  FrontEnd/PopUp/PopUp/Assets.xcassets/리뷰 접기더보기/ReviewDown.imageset/icon_NAV (33).png
  FrontEnd/PopUp/PopUp/Assets.xcassets/리뷰 접기더보기/ReviewUp.imageset/Contents.json
  FrontEnd/PopUp/PopUp/Assets.xcassets/리뷰 접기더보기/ReviewUp.imageset/icon_NAV (28).png
  FrontEnd/PopUp/PopUp/Assets.xcassets/리뷰 접기더보기/ReviewUp.imageset/icon_NAV (29).png
  FrontEnd/PopUp/PopUp/Assets.xcassets/리뷰 접기더보기/ReviewUp.imageset/icon_NAV (30).png
  FrontEnd/PopUp/PopUp/HomeView/Controller/MyPage/StoredPopUpViewController.swift
  FrontEnd/PopUp/PopUp/HomeView/Controller/PieceInfo/PieceInfoViewController.swift
  FrontEnd/PopUp/PopUp/HomeView/View/Main/Base.lproj/Main.storyboard
  FrontEnd/PopUp/PopUp/HomeView/View/MyPage/MyPage.storyboard
  FrontEnd/PopUp/PopUp/HomeView/View/MyPage/StoredTableViewCell.swift
  FrontEnd/PopUp/PopUp/HomeView/View/PieceInfo/PieceInfoViewController.storyboard
Labels: enhancement

#18 [Feat] 방문 조각 공유 기능 구현
  FrontEnd/PopUp/PopUp/HomeView/Controller/Piece/PieceSaveViewController.swift
  FrontEnd/PopUp/PopUp/HomeView/View/Main/PieceViewController.storyboard
Labels: enhancement

#19 [Feat] QR 인증
  FrontEnd/PopUp/PopUp.xcodeproj/project.pbxproj
  FrontEnd/PopUp/PopUp/HomeView/Controller/Main/CustomPresentationController.swift
  FrontEnd/PopUp/PopUp/HomeView/Controller/Main/QRViewController.swift
  FrontEnd/PopUp/PopUp/HomeView/Controller/Main/ViewController.swift
  FrontEnd/PopUp/PopUp/HomeView/Controller/Piece/MakePieceViewController.swift
  FrontEnd/PopUp/PopUp/HomeView/Controller/Piece/PieceSaveViewController.swift
  FrontEnd/PopUp/PopUp/HomeView/Controller/Piece/PieceViewController.swift
  FrontEnd/PopUp/PopUp/HomeView/View/Main/Base.lproj/Main.storyboard
  FrontEnd/PopUp/PopUp/HomeView/View/Main/PieceViewController.storyboard
  FrontEnd/PopUp/PopUp/HomeView/View/PieceView/MakePieceTableViewCell.swift
  FrontEnd/PopUp/PopUp/Info.plist
Labels: enhancement

#21 [Feat] recommand popup store collection view 구현
  FrontEnd/PopUp/PopUp.xcodeproj/project.pbxproj
  FrontEnd/PopUp/PopUp/HomeView/Controller/Main/RecommandCollectionViewCell.swift
  FrontEnd/PopUp/PopUp/HomeView/Controller/Main/RecommandPopupViewController.swift
  FrontEnd/PopUp/PopUp/HomeView/Controller/Main/ViewController.swift
  FrontEnd/PopUp/PopUp/HomeView/View/Main/Base.lproj/Main.storyboard
  FrontEnd/PopUp/PopUp/HomeView/View/Main/PieceViewController.storyboard
Labels: enhancement

#27 APIConstant, response structure 생성
  FrontEnd/PopUp/Podfile.lock
  FrontEnd/PopUp/Pods/Manifest.lock
  FrontEnd/PopUp/Pods/Target Support Files/Alamofire/Alamofire-Info.plist
  FrontEnd/PopUp/Pods/Target Support Files/Pods-PopUp-PopUpUITests/Pods-PopUp-PopUpUITests-Info.plist
  FrontEnd/PopUp/Pods/Target Support Files/Pods-PopUp-PopUpUITests/Pods-PopUp-PopUpUITests-frameworks.sh
  FrontEnd/PopUp/Pods/Target Support Files/Pods-PopUp-PopUpUITests/Pods-PopUp-PopUpUITests.debug.xcconfig
  FrontEnd/PopUp/Pods/Target Support Files/Pods-PopUp-PopUpUITests/Pods-PopUp-PopUpUITests.release.xcconfig
  FrontEnd/PopUp/Pods/Target Support Files/Pods-PopUp/Pods-PopUp-Info.plist
  FrontEnd/PopUp/Pods/Target Support Files/Pods-PopUp/Pods-PopUp-frameworks.sh
  FrontEnd/PopUp/Pods/Target Support Files/Pods-PopUp/Pods-PopUp.debug.xcconfig
  FrontEnd/PopUp/Pods/Target Support Files/Pods-PopUpTests/Pods-PopUpTests-Info.plist
  FrontEnd/PopUp/Pods/Target Support Files/Pods-PopUpTests/Pods-PopUpTests.debug.xcconfig
  FrontEnd/PopUp/Pods/Target Support Files/Pods-PopUpTests/Pods-PopUpTests.release.xcconfig
  FrontEnd/PopUp/PopUp.xcodeproj/project.pbxproj
  FrontEnd/PopUp/PopUp/HomeView/Model/Home/HomeAllPopupResponseData.swift
  FrontEnd/PopUp/PopUp/HomeView/Model/Home/HomeWeeklyHotResponseModel.swift
  FrontEnd/PopUp/PopUp/HomeView/Model/Manager/HomeManager.swift
  FrontEnd/PopUp/PopUp/HomeView/Model/NetWork/APIConstants.swift
  FrontEnd/PopUp/PopUp/HomeView/Model/PopupDetail/PopupDetailBookMarkResponseData.swift
  FrontEnd/PopUp/PopUp/HomeView/Model/PopupDetail/PopupDetailResponseData.swift
Labels: enhancement

#30 [Feat] alert
  FrontEnd/PopUp/PopUp.xcworkspace/xcuserdata/idonghyeon.xcuserdatad/UserInterfaceState.xcuserstate
  FrontEnd/PopUp/PopUp/HomeView/Controller/Main/NotificationViewController.swift
Labels: enhancement

#37 [Feat] LoginView 구현
  FrontEnd/PopUp/PopUp.xcodeproj/project.pbxproj
  FrontEnd/PopUp/PopUp/Assets.xcassets/BtnSet/password-hidden-icon.imageset/Contents.json
  FrontEnd/PopUp/PopUp/Assets.xcassets/BtnSet/password-hidden-icon.imageset/solar_eye-linear.png
  FrontEnd/PopUp/PopUp/Assets.xcassets/BtnSet/password-shown-icon.imageset/Contents.json
  FrontEnd/PopUp/PopUp/Assets.xcassets/BtnSet/password-shown-icon.imageset/solar_eye-linear.png
  FrontEnd/PopUp/PopUp/Assets.xcassets/Logo/LoginImage.imageset/Contents.json
  FrontEnd/PopUp/PopUp/Assets.xcassets/Logo/LoginImage.imageset/Frame 2609686.png
  FrontEnd/PopUp/PopUp/Assets.xcassets/Logo/LoginImage.imageset/Frame 2609687.png
  FrontEnd/PopUp/PopUp/Assets.xcassets/Logo/LoginImage.imageset/Image.png
  FrontEnd/PopUp/PopUp/HomeView/Controller/Login/Login2ViewController.swift
  FrontEnd/PopUp/PopUp/HomeView/Controller/Main/ViewController.swift
  FrontEnd/PopUp/PopUp/HomeView/View/LoginView/LoginView.storyboard
Labels: enhancement

#46 [Feat] make piece
  FrontEnd/PopUp/PopUp/HomeView/Controller/Piece/MakePiecePictureViewController.swift
  FrontEnd/PopUp/PopUp/HomeView/Controller/Piece/MakePieceViewController.swift
  FrontEnd/PopUp/PopUp/HomeView/Controller/Piece/PieceSaveViewController.swift
  FrontEnd/PopUp/PopUp/HomeView/Controller/Piece/PieceViewController.swift
  FrontEnd/PopUp/PopUp/HomeView/View/Main/PieceViewController.storyboard
Labels: enhancement

#48 [Feat] main to piece detail view
  FrontEnd/PopUp/PopUp/AppDelegate.swift
  FrontEnd/PopUp/PopUp/HomeView/Controller/Main/ViewController.swift
  FrontEnd/PopUp/PopUp/HomeView/Controller/Piece/PieceDetailViewController.swift
  FrontEnd/PopUp/PopUp/HomeView/Controller/Piece/PieceViewController.swift
  FrontEnd/PopUp/PopUp/HomeView/Controller/Piece/PieceViewController2.swift
Labels: enhancement

#55 fork repo Merge
  BackEnd/.github/workflows/deploy.yml
  BackEnd/.gitignore
  BackEnd/appspec.yml
  BackEnd/build.gradle
  BackEnd/gradle/wrapper/gradle-wrapper.jar
  BackEnd/gradle/wrapper/gradle-wrapper.properties
  BackEnd/gradlew
  BackEnd/gradlew.bat
  BackEnd/scripts/start.sh
  BackEnd/scripts/stop.sh
  BackEnd/settings.gradle
  BackEnd/src/main/java/com/example/popup/PopupApplication.java
  BackEnd/src/main/java/com/example/popup/config/JasyptConfig.java
  BackEnd/src/main/java/com/example/popup/controller/HomeController.java
  BackEnd/src/main/java/com/example/popup/controller/MemberController.java
  BackEnd/src/main/java/com/example/popup/controller/MyPageController.java
  BackEnd/src/main/java/com/example/popup/controller/PopupController.java
  BackEnd/src/main/java/com/example/popup/controller/ReviewController.java
  BackEnd/src/main/java/com/example/popup/controller/SearchController.java
  BackEnd/src/main/java/com/example/popup/domain/Member.java
  BackEnd/src/main/java/com/example/popup/domain/Popup.java
  BackEnd/src/main/java/com/example/popup/domain/Review.java
  BackEnd/src/main/java/com/example/popup/dto/ReqDto/BookMarkReqDto.java
  BackEnd/src/main/java/com/example/popup/dto/ReqDto/MemberReqDto.java
  BackEnd/src/main/java/com/example/popup/dto/ReqDto/PopupReqDto.java
  BackEnd/src/main/java/com/example/popup/dto/ReqDto/ReviewReqDto.java
  BackEnd/src/main/java/com/example/popup/dto/ReqDto/SearchReqDto.java
  BackEnd/src/main/java/com/example/popup/dto/ResDto/GlobalResDto.java
  BackEnd/src/main/java/com/example/popup/dto/ResDto/PopupHomeResDto.java
  BackEnd/src/main/java/com/example/popup/dto/ResDto/PopupOneResDto.java
  BackEnd/src/main/java/com/example/popup/dto/ResDto/PopupThemeResDto.java
  BackEnd/src/main/java/com/example/popup/exception/CustomException.java
  BackEnd/src/main/java/com/example/popup/exception/ErrorCode.java
  BackEnd/src/main/java/com/example/popup/exception/ErrorResponse.java
  BackEnd/src/main/java/com/example/popup/exception/ExceptionHandling.java
  BackEnd/src/main/java/com/example/popup/repository/MemberRepository.java
  BackEnd/src/main/java/com/example/popup/repository/PopupRepository.java
  BackEnd/src/main/java/com/example/popup/repository/ReviewRepository.java
  BackEnd/src/main/java/com/example/popup/service/HomeService.java
  BackEnd/src/main/java/com/example/popup/service/MemberService.java
  BackEnd/src/main/java/com/example/popup/service/MyPageService.java
  BackEnd/src/main/java/com/example/popup/service/PopupService.java
  BackEnd/src/main/java/com/example/popup/service/ReviewService.java
  BackEnd/src/main/java/com/example/popup/service/SearchService.java
  BackEnd/src/main/resources/application.yml
  BackEnd/src/test/java/com/example/popup/PopupApplicationTests.java
  README.md
Labels: enhancement
